travis:
  secure:
    BINSTAR_TOKEN: Unw5Zo1t/MFx5UcVelAR6K4DmDbLMIt8xx6RjhHcJ9xMKDFlLPMDkHCYHnJ6o9yaOscAo1KhbPa8VRw6zYN0N1AMikjacVMXjqglkQzBvOxzO8HO/npy6OFuyZwa9zAGhlrIAw5UD4avVTUcDvsv1cYarUACb+Ce6ggt2zx4oTlDCmWXN/cRKnOL/W2oWO1ypKF7YbiUCwB2cq8G8i2ryJX7Wl4JBu83LVNWWZKCx6brWIUYqHveXP+xEPlR2c4lqzyo5rDToZcfLfLhgCkRiYFmZ7D6Nlu3jNh0RoagspmUjtQ2yF3jjXHDj+yTlB9SQcsnNzicuB7fiUE1xIjh3dEDUTuvekXz5eM1Pqph3MUqPxjiua2zD1q8scw12pS+rF22EEahX6NAUDU9wzPpH8e/nNkDoIXi61cggoIgOS5OI1gxPAC/Di42r3At3mHLec+0W9VbbwnUOlTbXurum4Wv9gENDP1Lc6JyF/hCy+p72kKZaVW903W7kjxJqyRMCZgtFv9Q3rMJn3p3/D3h0UCY+1ini5qZcWl6k9tcSt0L83PCFdCji5rpSuki7mxYu7ipjbkc22/5+94LenO1U6T9u3vsJ/zcqnJ75Tkwor2Sj4bvITYuvtRG3Dk/9XuGu9USaUGg3Ukj7cPPRjMz4B/plbOUI4EQIVhS9WIRJSQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
