appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: j4pzReXSL/f8Hdqxuf6fQSYgRQOc4qLHC1M0QuLNguYFUXRcPUkh/5d2mzmb/BcUW6ZfSUrm9co2ibKXUKfosx7di7uZ/ikgoLAiCG+t/khSgus+LBOvbIbNn95nakd2RR284MWocKfSj1BYlP+x8CYHwC660sd4tyQ5/+JYhzT3jZv0mmaEu+ZigQQcB0t3ETcWl3hUifZObLhdDJXR03J5AWIqG9NoTChwqlbEIwsPqNvvkPqPDRxm6VRfCsmRxfqz+wt61xC2Kn5Bheb6ARiZKAKbQF9kRAUlH0fc7Fsal19yAMk0R5cUmcd+fTjG645pKhNfjMvwtGaEixEKrNB7eJmGM3FObpuzphf6/H1I6PCls6N86vPIbyG+zW+FWn0wZOBsbbcTeXBK9UwtoJfWHmDxG2oa6VLrdXVZXZzOQDD+f4bTWVPf2soGbwV8eAJr7O9PI57rLbhgR0E4teagX4jsin/olTkdp1OYkjUfdmBzgrbh/VGzHhFBDJtlPOc83fWYVWttzyzm+25yA5zCjLB4w0mUk7bhjbwNOL8C7FliHy+0JzS3bBFXI4OlK5WEqX+j+npbuj+Qq5r/HvrBLXdrP+KsLPNq+NcnVNDoO81WYAdObYofQbxMvKFOcz0rEE8PpR32Ozt9TUlbgYROoU8eYQnTAAyStMXQaVw=
conda_forge_output_validation: true
